---
name: micromamba/jupyter application

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: ['*']

permissions:
  contents: read

env:
  UV_MALWARE_CHECK: "1"
  python_beta: "3.15"  # Latest pre-release version for beta tests, see logs
  python_beta_on: "3.14"

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: "macos-latest"
            platform: "darwin"
            os_pkgs: "fortran-compiler"

          - os: "macos-26-intel"
            python-version: "3.14"
            platform: "darwin-intel"
            os_pkgs: "fortran-compiler"

          - os: "ubuntu-latest"
            platform: "linux"
            os_pkgs: "mkl-devel"

          - os: "windows-latest"
            platform: "win32"
            os_pkgs: "m2w64-gcc-fortran mkl-devel"

          # For fortran compiler example
          - os: "ubuntu-latest"
            python-version: "3.14"
            platform: "linux"
            os_pkgs: "flang libflang-rt mkl-devel"

          - os: "windows-latest"
            python-version: "3.14"
            platform: "win32"
            os_pkgs: "flang flang-rt_win-64 m2w64-gcc-fortran mkl-devel"

    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v6

      - uses: mamba-org/setup-micromamba@v3
        env:
          CACHE_NUMBER: 0  # modify to reset cache manually
        with:
          init-shell: bash
          post-cleanup: none
          environment-name: test-env
          environment-file: tests/base-environment.yml
          create-args: >-
            python=${{ matrix.python-version }} ${{ matrix.os_pkgs }}
          cache-environment: true
          cache-downloads: true

      - name: Setup `uv` with caches by default
        uses: astral-sh/setup-uv@v8.1.0

      - name: Lint with ruff & yamllint
        run: |
          if [ "${{ matrix.platform }}" != "win32" ]; then
            # ``yamllint`` bug workaround
            # https://github.com/adrienverge/yamllint/issues/347
            yamllint .
          fi
          uv run --group dev ruff check .
          uv run --group dev ruff format --check .

      - name: Workaround conda pkg-config BLAS/LAPACK
        run: |
          if pkg-config --exists mkl-sdl; then
            mkl_sdl_dir="`pkg-config --variable=pcfiledir mkl-sdl`"
            mkl_sdl="$mkl_sdl_dir/mkl-sdl.pc"
            if pkg-config --exists blas; then
              echo "Have blas in `pkg-config --variable=pcfiledir blas`"
            else
              blas="$mkl_sdl_dir/blas.pc"
              echo "Hack, use: $mkl_sdl as $blas"
              cp "$mkl_sdl" "$blas"
            fi
            if pkg-config --exists lapack; then
              echo "Have lapack in `pkg-config --variable=pcfiledir lapack`"
            else
              lapack="$mkl_sdl_dir/lapack.pc"
              echo "Hack, use: $mkl_sdl as $lapack"
              cp "$mkl_sdl" "$lapack"
            fi
          else
            echo "Don't have mkl-sdl"
          fi

      - name: Precheck f2py
        run: |
          echo "python: " ; python --version
          echo "numpy:  " ; python -c "import numpy; print(numpy.__version__)"
          echo "f2py:   " ; python -m numpy.f2py -v
          echo "pytest: " ; python -m pytest --version
          echo "ipython:" ; ipython --version
          echo "meson:     " ; meson -v
          echo "ninja:     " ; ninja --version
          cmake --version
          echo "pkg-config:" ; pkg-config --version
          type pkg-config
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"

          pkg-config --list-all

          ld_lapack="--dep lapack"

          python -m numpy.f2py --backend meson --verbose -c tests/fib1.f -m fib1
          python -c 'if 1:
            import fib1
            import numpy as np

            a=np.zeros(8,"d")
            fib1.fib(a)
            print(a)
            '

          if pkg-config --exists blas && pkg-config --exists lapack; then
            python -m numpy.f2py --backend meson --verbose \
              -c tests/solve.f90 -m solve $ld_lapack
            python -c 'if 1:
              from solve import solve
              import numpy as np

              A = np.array([[1, 2.5], [-3, 4]])
              b = np.array([1, 2.5])
              x = solve(A, b)
              print(x)
              np.testing.assert_allclose(x, np.linalg.solve(A, b))
              '
          else
            echo "Skipping LAPACK precheck (blas/lapack not found via" \
              "pkg-config)."
          fi

      - name: Test with pytest
        run: |
          PYTHONUTF8=1 JUPYTER_PLATFORM_DIRS=1 uv run --group dev pytest

      - name: Beta test on Python beta
        if: env.python_beta_on == matrix.python-version
        run: |
          if [ "${{ matrix.platform }}" != "win32" ]; then
            PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 \
              PYTHONUTF8=1 JUPYTER_PLATFORM_DIRS=1 uv \
              run --group dev --python=python${{ env.python_beta }} pytest
          else
            echo "Unsuitable gcc for build of NumPy"  # FIXME
            echo "PATH=$PATH"
            gcc --version || echo No gcc
          fi
...
