---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-3-Clause
#
name: Publish to PyPI

on:  # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
      - run: uv build
      - name: Generate publish attestations
        # v0.0.6
        uses: astral-sh/attest-action@f589a42a7efb6fe400b4f400de60b4bc90390027
      - run: uv publish
